### ISSUE TITLE
Invalid buddy ID given (must be 76 characters long)

### ISSUE THREAD

**Issue by strk** [jin-eld/tox-prpl#35]
I'm playing with qTox <-> Pidgin communication on the same machine, but when trying to add a buddy (is that how you send friend requests via pidgin?) by using the friend's Tox ID, I get this error message:

```
Invalid buddy ID given (must be 76 characters long)
```

The TOX ID as exported by qTox is 65 characters long.

**Comment by jin-eld** [comment]
Tried qTox vs Pidgin with the recent release, did not see any issues.
