### ISSUE TITLE
The current value for TOXPRPL_ID breaks telepathy-haze because it contains an underscore

### ISSUE THREAD

**Issue by therealpxc** [jin-eld/tox-prpl#48]
telepathy-haze complains about an invalid ID because the underscore breaks it. I changed TOXPRPL_ID="prpl-jin_eld-tox" to TOXPRPL_ID="Tox" in the source, recompiled and reinstalled, and telepathy-haze worked again. I'd like to use Tox through KDE's Telepathy front-end, and this actually breaks all libpurple-based protocols for Telepathy as it is.

Tested on Linux Mint 17.1 (based on Ubuntu 14.04) using the Tox packages from KYTV's ppa.

You can verify that telepathy-haze is broken and check the error message by running /usr/lib/telepathy/telepathy-haze from a command-line on any system containing pidgin-tox and Telepathy.

**Comment by jin-eld** [comment]
Hi,

On Thu, Jan 01, 2015 at 10:40:11PM -0800, Patrick Callahan wrote:
> telepathy-haze complains about an invalid ID because the underscore breaks it.
> I changed TOXPRPL_ID="prpl-jin_eld-tox" to TOXPRPL_ID="Tox" in the source,
> recompiled and reinstalled, and telepathy-haze worked again. I'd like to use
> Tox through KDE's Telepathy front-end, and this actually breaks all
> libpurple-based protocols for Telepathy as it is.
> 
> Tested on Linux Mint 17.1 (based on Ubuntu 14.04) using the Tox packages from
> KYTV's ppa.
> 
> You can verify that telepathy-haze is broken and check the error message by
> running /usr/lib/telepathy/telepathy-haze from a command-line on any system
> containing pidgin-tox and Telepathy.

I suggest to submit a bug report to the telepathy-haze people:

https://developer.pidgin.im/doxygen/2.5.2/html/plugin-ids.html

As you can see there the toxprpl id goes along with the libpurple standards,
also compare to the "Examples of Well-Chosen Plugin IDs".

There is some freedom of choice in the username selection, i.e. it could
be an IRC name as well which in my case would be Jin^eLD which I could
use as a temporary workaround, but I'd actually prefer that bugs are
fixed where they occur, which in this case is not in tox-prpl.

**Comment by therealpxc** [comment]
Thanks for clarifying that. The docs page appears to be down. I'll take your word for now, and file a bug report with the Pidgin people once I can glance at it, linking both to it and this bug report in the bug report I file with them.

**Comment by jin-eld** [comment]
On Sat, Jan 03, 2015 at 12:19:40PM -0800, Patrick Callahan wrote:
> Thanks for clarifying that. The docs page appears to be down. I'll take your
> word for now, and file a bug report with the Pidgin people once I can glance at
> it, linking both to it and this bug report in the bug report I file with them.

Hmm, the page https://developer.pidgin.im/doxygen/2.5.2/html/plugin-ids.html
loads here without problems, anyway if it helps I'll paste the relevant
passages for you:
 
 Introduction
Every plugin contains a unique identifier to prevent duplicate plugin loading and conflicts. Third-party plugins (that is, plugins written by anyone who is not a libpurple, Pidgin, or Finch developer) are expected to use a plugin ID that follows a specific format. This format categorizes plugins and makes duplicate IDs highly unlikely.
Format
The basic format of a plugin ID is as follows:

type-username-pluginname

The type indicator specifies the type of plugin. This must be one of the following:

    core - A core libpurple plugin, capable of being loaded in any program using libpurple. Core plugins may not contain any UI-specific code.
    prpl - A protocol plugin. This is a special type of core plugin, which provides libpurple the ability to connect to another IM or chat network.
    lopl - A loader plugin, which loads scripts as plugins. Perl and Tcl plugins are made possible by loader plugins.
    gtk - A GTK+ 2.x (a.k.a. Pidgin) plugin. These plugins may use GTK+ code, but may not use window toolkit code, such as X11, Win32, Cocoa, or Carbon.
    gtk-x11 - A GTK+ 2.x plugin that uses X11 code. These plugins may use both GTK+ code and X11 code, allowing to hook into features specific to X11.
    gtk-win32 - A GTK+ plugin that uses Win32 code. These plugins may use both GTK+ code and Win32 code, allowing to hook into features available on Windows.
    gnt - A GNT (a.k.a. Finch) plugin. These plugins may use GNT code.
    qpe - A plugin for the (now-abandoned) Qutopia user interface.

The username must be a unique identifier for you. It should be your http://developer.pidgin.im Trac user ID. Failing that, you could use your SourceForge user ID or your Freenode IRC nickname, if you have either. The http://developer.pidgin.im Trac user ID is preferred. Do not leave this field blank!

The pluginname is the name of your plugin. It is usually all lowercase letters and matches the static plugin ID (the first argument to the PURPLE_INIT_PLUGIN() macro call), although it can be anything you like. Do not include version information in the plugin ID--the PurplePluginInfo structure already has a field for this.
One Last Rule for Plugin IDs
The last rule of plugin IDs is the most important of all. Plugin IDs may NOT contain spaces. If you need a space, use another hyphen (-).

...


 Examples of Well-Chosen Plugin IDs
The following is a list of well-chosen Plugin IDs listing a few good examples.

    "gtk-amc_grim-guifications" - This is the plugin ID for the Guifications 2.x plugin.
    "gtk-rlaager-album" - This is the plugin ID for the Album plugin, which is now part of the Purple Plugin Pack. Its ID follows the rules because its life started prior to its inclusion in the Plugin Pack.
    "core-rlaager-irchelper" - This is the plugin ID for the IRC Helper plugin, which is now part of the Purple Plugin Pack. Its ID follows the rules because its life started prior to its inclusion in the Plugin Pack.

**Comment by therealpxc** [comment]
Huh. I think it was just this library's connection. I'm now using my phone's internet connection and the page loads fine. I'll take this to the telepathy-haze people next. Here's the full text of what was happening (the first instance is my ‘fixed’ package and the second instance is the original), for the record and googleability.

	pxc@davetim ~> /usr/lib/telepathy/telepathy-haze 

	** (haze:7997): CRITICAL **: purple_value_new: assertion 'type != PURPLE_TYPE_UNKNOWN' failed

	** (haze:7997): CRITICAL **: purple_value_new: assertion 'type != PURPLE_TYPE_UNKNOWN' failed

	(haze:7997): haze-WARNING **: prpl 'Tox' has a dumb id; spank its author
	tp-glib-Message: Exiting
	pxc@davetim ~> sudo apt-get install --reinstall pidgin-tox
	[sudo] password for pxc: 
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
	Need to get 0 B/30.0 kB of archives.
	After this operation, 0 B of additional disk space will be used.
	(Reading database ... 337872 files and directories currently installed.)
	Preparing to unpack .../pidgin-tox_0.4.2+git20141202.r122-1~trusty+1_amd64.deb ...
	Unpacking pidgin-tox (0.4.2+git20141202.r122-1~trusty+1) over (0.4.2+git20141202.r122-1~trusty+1) ...
	Setting up pidgin-tox (0.4.2+git20141202.r122-1~trusty+1) ...
	pxc@davetim ~> /usr/lib/telepathy/telepathy-haze 

	** (haze:8134): CRITICAL **: purple_value_new: assertion 'type != PURPLE_TYPE_UNKNOWN' failed

	** (haze:8134): CRITICAL **: purple_value_new: assertion 'type != PURPLE_TYPE_UNKNOWN' failed

	(haze:8134): tp-glib-CRITICAL **: Not a valid protocol name because character '_' is not an ASCII letter, digit or hyphen/minus: jin_eld-tox
	fish: Job 1, “/usr/lib/telepathy/telepathy-haze ” terminated by signal SIGTRAP (Trace or breakpoint trap)

**Comment by v-fox** [comment]
Ah, i came here to complain and post that log snipset too but apaprently was too slow.
It's pretty damn ridiculous that they've gone through trouble coding such verbose warning and "error" detection but not "error" handling without suicide. Made me 90% sure that it's tox-prpl's fault.

**Comment by jin-eld** [comment]
On Wed, Feb 04, 2015 at 05:06:28AM -0800, Sergey Kondakov wrote:
> Ah, i came here to complain and post that log snipset too but apaprently was
> too slow.
> It's pretty damn ridiculous that they've gone through trouble coding such
> verbose warning and "error" detection but not "error" handling without suicide.
> Made me 90% sure that it's tox-prpl's fault.

Well, let's put it that way: it's my first purple plugin and I had no
clue that clients may reject the id at all... patches are welcome ;)

**Comment by v-fox** [comment]
> Well, let's put it that way: it's my first purple plugin and I had no clue that clients may reject the id at all... patches are welcome ;)

I think i will just remove... haze and everything that depends on it from my system and the live distribution :] It's a shim anyway that hasn't been updated for ages and with libpurple alone tox-prpl seems to load fine.
