### ISSUE TITLE
Intermittent Crashes (Windows 7, Pidgin 2.10.11, tox-prpl 0.4.1)

### ISSUE THREAD

**Issue by redyoshi49q** [jin-eld/tox-prpl#53]
I've gotten a few intermittent and seemingly random crashes in Pidgin recently, and after having looked at my recent crash backtraces, it seems that they were caused by tox-prpl.  I have also recorded debug logs, but they're not even remotely informative, so they're not included in this bug report.

I've pasted an example backtrace below.  Since I'm running tox-prpl on Windows, I don't know whether or not this issue also occurs on Linux.

```
Error occured on Monday, March 9, 2015 at 17:39:58.

Windows Version 6.1 Build 7601 Service Pack 1

C:\Program Files (x86)\Pidgin\pidgin.exe caused an Access Violation at location 02b06109 in module C:\Program Files (x86)\Pidgin\pthreadGC2.dll Reading from location 00000008.

Registers:
eax=02b060f8 ebx=00000000 ecx=01ff9168 edx=07d484e8 esi=07d687ec edi=0028ebd7
eip=02b06109 esp=0028eba0 ebp=0028ec48 iopl=0         nv up ei pl nz ac pe cy
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210213

Call stack:
         C:\Program Files (x86)\Pidgin\pthreadGC2.dll [2.9.1.0]
02B06109 C:\Program Files (x86)\Pidgin\pthreadGC2.dll  pthread_mutex_unlock
0301A8F9 C:\Program Files (x86)\Pidgin\libtoxcore-0.dll  bs_list_trim
0301B1CB C:\Program Files (x86)\Pidgin\libtoxcore-0.dll  bs_list_trim
0301E3EE C:\Program Files (x86)\Pidgin\libtoxcore-0.dll  crypto_kill
0301E779 C:\Program Files (x86)\Pidgin\libtoxcore-0.dll  new_net_crypto
0301E7C9 C:\Program Files (x86)\Pidgin\libtoxcore-0.dll  do_net_crypto
0300F9DA C:\Program Files (x86)\Pidgin\libtoxcore-0.dll  do_messenger
030274E1 C:\Program Files (x86)\Pidgin\libtoxcore-0.dll  tox_do
6814206C C:\Program Files (x86)\Pidgin\plugins\libtox.dll
         C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll [2.28.8.0]
685EC49E C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_source_get_time
685EB167 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_context_dispatch
685EB90D C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_context_dispatch
685EBD9D C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_loop_run
         C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
02774260 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_main
```

**Comment by jin-eld** [comment]
On Mon, Mar 09, 2015 at 10:51:43PM -0700, redyoshi49q wrote:
> I've gotten a few intermittent and seemingly random crashes in Pidgin recently,
> and after having looked at my recent crash backtraces, it seems that they were
> caused by tox-prpl. I have also recorded debug logs, but they're not even
> remotely informative, so they're not included in this bug report.

judging by your stack trace it looks like tox core library is crashing,
I guess it's worth to try the latest version of the lib from git.

I was planning to finally release an update for the plugin, maybe I'll
find some time for it this week, let's see.

**Comment by alexolog** [comment]
What is the status of the Windows plugin?
The web page says it was taken down due to instability, but that was almost 2 years ago.

**Comment by jin-eld** [comment]
On Sat, Aug 06, 2016 at 07:48:29AM -0700, alexolog wrote:
> What is the status of the Windows plugin?
> The web page says it was taken down due to instability, but that was almost 2
> years ago.

The staus is that the plugin as such (for any platform) is out of date,
I had no time to continue development and noone else seemed interested
enough to pick it up.

**Comment by jin-eld** [comment]
Closing this for now since we do not have an up to date win32 build, the 0.4.x version is obsolete.
