### ISSUE TITLE
New Toxcore API

### ISSUE THREAD

**Issue by urras** [jin-eld/tox-prpl#54]
Toxcore has a new API that was merged into master a while ago. This means that tox-prpl will no longer work with the current version of Toxcore. Are there any plans in the future to port tox-prpl to the new API, @jin-eld?

**Comment by jin-eld** [comment]
On Fri, Apr 03, 2015 at 09:23:04AM -0700, Nick Hovaker wrote:
> Toxcore has a new API that was merged into master a while ago. This means that
> tox-prpl will no longer work with the current version of Toxcore. Are there any
> plans in the future to port tox-prpl to the new API, @jin-eld?

I did indeed plan to have a look at it, just did not have the time yet,
maybe I'll find some time this weekend, let's see.

**Comment by kaptoxic** [comment]
+1 :+1:

**Comment by red-9m** [comment]
One more vote in favor of new API

**Comment by kaptoxic** [comment]
What is the status--are the changes to the API too big and cannot be handled easily?

**Comment by jin-eld** [comment]
On Wed, May 13, 2015 at 08:42:56PM -0700, Ivan Kuraj wrote:
> What is the status--are the changes to the API too big and cannot be handled
> easily?

Mostly my limited time. I am about half way through, but I did not have
time to continue during the last two weeks.

**Comment by kaptoxic** [comment]
I see. Not sure if you need any help (or if we can provide any help). Anyway, good luck.

And yeah, you should perhaps have some sort of "buy me a beer"/donate option :smile:

**Comment by jin-eld** [comment]
On Thu, May 14, 2015 at 10:02:13AM -0700, Ivan Kuraj wrote:
> I see. Not sure if you need any help (or if we can provide any help). Anyway,
> good luck.

Well, I will finish the first part and push it to some branch, if
someone feels like helping out with file transfer - that'd be great.

> And yeah, you should perhaps have some sort of "buy me a beer"/donate option
> :smile:

Hmm, I don't drink beer :) But "buy me some spare parts for UAZ-469"
would surely work ;)

**Comment by kaptoxic** [comment]
:) :) :) Okay, cool--we will stay tuned.

**Comment by Xylemon** [comment]
Any update on this?

**Comment by jin-eld** [comment]
On Wed, Jun 03, 2015 at 07:03:15AM -0700, Gethyn ThomasQuail wrote:
> Any update on this?

I poked around a little, but still did not find the time to finish it,
I pushed the branch now (it does not compile yet), so you can see where
I am at and/or if you feel like it - help me out. I'll be away this
whole weekend again, so I don't think I'll be able to do much, sorry :P

**Comment by locke87** [comment]
There is no such thing as a transition guide to the new API, right? I started working on the file transfer stuff, however, I don't know how much time I will find in the coming weeks...

**Comment by jin-eld** [comment]
On Sat, Jun 13, 2015 at 08:07:50AM -0700, Felix Mauch wrote:
> There is no such thing as a transition guide to the new API, right? I started
> working on the file transfer stuff, however, I don't know how much time I will
> find in the coming weeks...

Not really and this was also a problem for me, you can look here to get
some clues:

https://github.com/irungentoo/toxcore/commit/3fab80409879b925979ee1a6bb0492c69bcfb7d0

The guys in #tox-dev are very helpful as well.

**Comment by rodneyrod** [comment]
How has the progress with this been going?

**Comment by locke87** [comment]
Progress is, that I managed to get it running again, but after going offline again, I have to re-add contacts. Right now I'm in the last weeks of my master's thesis, so I guess, I won't find any time for it the next 3-4 weeks. However, afterwards I would be happy to finish this :)

**Comment by jin-eld** [comment]
On Fri, Jun 26, 2015 at 12:52:23AM -0700, Felix Mauch wrote:
> Progress is, that I managed to get it running again, but after going offline
> again, I have to re-add contacts. Right now I'm in the last weeks of my
> master's thesis, so I guess, I won't find any time for it the next 3-4 weeks.
> However, afterwards I would be happy to finish this :)

Could you please push your stuff somewhere? I could have a look at the
contacts issue, my main problem was figuring out the old->new API
mapping and from what I understand you got that part done?

**Comment by locke87** [comment]
Hi, I pushed my changes to my fork. 

Cheers
Felix

**Comment by akaWolf** [comment]
Anyway, there is one more package, which using old api: ratox.
#8563

**Comment by quininer** [comment]
@locke87 
maybe you should send a PR :D

**Comment by locke87** [comment]
Sorry, I haven't worked with github very much, so far...

**Comment by selurvedu** [comment]
Thanks @locke87, that #57 looks nice. Finally I can compile tox-prpl. :+1:

**Comment by kaptoxic** [comment]
Nice, looking forward to seeing this merged :+1:

**Comment by mkolchin** [comment]
The movement will be?

**Comment by jin-eld** [comment]
On Thu, Sep 03, 2015 at 03:45:01AM -0700, Mikhail Kolchin wrote:
> The movement will be?

I'm struggling to understand how file transfers work (actually I did not
implement that myself in the earlier version but received a patch), apart from
file transfers it's not so far away from being done, but I really did not
find any time..

It's tne new-api2 branch with the patch from Felix, tried after a while and
it does not compile anymore, I guess some more changes happened in the
meantime...

**Comment by rodneyrod** [comment]
Well either way, I can't wait to see this in a finished product.
File transfers and AV et al aren't really important to me personally, getting text chat up and running again would be more than enough.

**Comment by kaptoxic** [comment]
I agree with @rodneyrod

**Comment by aaannndddyyy** [comment]
+1

**Comment by Xylemon** [comment]
I tried the new API patch from Felix, it compiled fine but sadly it seems I can't connect. Whether I import or create a new account noting seems to happen. I even tried setting a different node, but to no avail.

**Comment by aaannndddyyy** [comment]
@Xylemon that patch is old and toxcore has changed considerable since then.
so unless a new patch comes, tox-prpl is dead.

**Comment by iphydf** [comment]
https://wiki.tox.chat/developers/gsoc/2016/ideas

@jin-eld if you can make an idea proposal in the format suggested on the GSoC ideas page, we can include it, and perhaps sometime will feel like reviving and enhancing the plugin.

**Comment by jin-eld** [comment]
On Thu, Feb 11, 2016 at 04:09:34AM -0800, iphydf wrote:
> https://wiki.tox.chat/developers/gsoc/2016/ideas
> 
> @jin-eld if you can make an idea proposal in the format suggested on the GSoC
> ideas page, we can include it, and perhaps sometime will feel like reviving and
> enhancing the plugin.

Sounds good, I'm really not likely to pick it up anytime soon, so if we
can find someone who can build on that code - that'd be great.

I'll have a look at the ideas page tonight and will hopefully write
something down that you can use.

**Comment by jin-eld** [comment]
Release 0.5.1 is out, the plugin is now finally synced with the most recent Tox API.
