### ISSUE TITLE
Install Error with latest toxcore

### ISSUE THREAD

**Issue by HaoZeke** [jin-eld/tox-prpl#56]
The steps followed were
git clone
cd dir
autoreconf -i
./configure
make

The error is 
../src/toxprpl.c:1369:14: error: ‘TOX_FAERR_TOOLONG’ undeclared (first use in this function)
         case TOX_FAERR_TOOLONG:
              ^
../src/toxprpl.c:1372:14: error: ‘TOX_FAERR_NOMESSAGE’ undeclared (first use in this function)
         case TOX_FAERR_NOMESSAGE:
              ^
../src/toxprpl.c:1375:14: error: ‘TOX_FAERR_OWNKEY’ undeclared (first use in this function)
         case TOX_FAERR_OWNKEY:
              ^
../src/toxprpl.c:1378:14: error: ‘TOX_FAERR_ALREADYSENT’ undeclared (first use in this function)
         case TOX_FAERR_ALREADYSENT:
              ^
../src/toxprpl.c:1381:14: error: ‘TOX_FAERR_BADCHECKSUM’ undeclared (first use in this function)
         case TOX_FAERR_BADCHECKSUM:
              ^
../src/toxprpl.c:1384:14: error: ‘TOX_FAERR_SETNEWNOSPAM’ undeclared (first use in this function)
         case TOX_FAERR_SETNEWNOSPAM:
              ^
../src/toxprpl.c:1387:14: error: ‘TOX_FAERR_NOMEM’ undeclared (first use in this function)
         case TOX_FAERR_NOMEM:
              ^
../src/toxprpl.c:1390:14: error: ‘TOX_FAERR_UNKNOWN’ undeclared (first use in this function)
         case TOX_FAERR_UNKNOWN:
              ^
../src/toxprpl.c: In function ‘toxprpl_add_to_buddylist’:
../src/toxprpl.c:1455:5: error: unknown type name ‘TOX_USERSTATUS’
     TOX_USERSTATUS userstatus = tox_get_user_status(plugin->tox, ret);
     ^
../src/toxprpl.c: In function ‘toxprpl_add_buddy’:
../src/toxprpl.c:1472:33: error: ‘TOX_FRIEND_ADDRESS_SIZE’ undeclared (first use in this function)
     if (strlen(buddy->name) != (TOX_FRIEND_ADDRESS_SIZE * 2))
                                 ^
../src/toxprpl.c:1495:47: error: ‘TOX_CLIENT_ID_SIZE’ undeclared (first use in this function)
     gchar *cut = g_ascii_strdown(buddy->name, TOX_CLIENT_ID_SIZE * 2 + 1);
                                               ^
../src/toxprpl.c: In function ‘toxprpl_remove_buddy’:
../src/toxprpl.c:1514:9: warning: implicit declaration of function ‘tox_del_friend’ [-Wimplicit-function-declaration]
         tox_del_friend(plugin->tox, buddy_data->tox_friendlist_number);
         ^
../src/toxprpl.c: In function ‘toxprpl_action_show_id_dialog’:
../src/toxprpl.c:1534:20: error: ‘TOX_FRIEND_ADDRESS_SIZE’ undeclared (first use in this function)
     uint8_t bin_id[TOX_FRIEND_ADDRESS_SIZE];
                    ^
../src/toxprpl.c: In function ‘toxprpl_export_account_dialog’:
../src/toxprpl.c:1644:20: error: ‘TOX_FRIEND_ADDRESS_SIZE’ undeclared (first use in this function)
     uint8_t bin_id[TOX_FRIEND_ADDRESS_SIZE];
                    ^
../src/toxprpl.c:1647:15: error: ‘TOX_CLIENT_ID_SIZE’ undeclared (first use in this function)
     strcpy(id+TOX_CLIENT_ID_SIZE, ".tox\0"); // insert extension instead of nos
               ^
../src/toxprpl.c: In function ‘toxprpl_can_receive_file’:
../src/toxprpl.c:1716:12: warning: implicit declaration of function ‘tox_get_friend_connection_status’ [-Wimplicit-function-declaration]
     return tox_get_friend_connection_status(plugin->tox,
            ^
../src/toxprpl.c: In function ‘toxprpl_xfer_init’:
../src/toxprpl.c:1825:26: warning: implicit declaration of function ‘tox_new_file_sender’ [-Wimplicit-function-declaration]
         int filenumber = tox_new_file_sender(plugin->tox, friendnumber, filesiz
                          ^
../src/toxprpl.c:1835:9: warning: implicit declaration of function ‘tox_file_send_control’ [-Wimplicit-function-declaration]
         tox_file_send_control(xfer_data->tox, xfer_data->friendnumber, 1,
         ^
../src/toxprpl.c:1836:36: error: ‘TOX_FILECONTROL_ACCEPT’ undeclared (first use in this function)
             xfer_data->filenumber, TOX_FILECONTROL_ACCEPT, NULL, 0);
                                    ^
In file included from /usr/lib/glib-2.0/include/glibconfig.h:9:0,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from ../src/toxprpl.c:53:
../src/toxprpl.c: In function ‘toxprpl_xfer_write’:
../src/toxprpl.c:1851:23: warning: implicit declaration of function ‘tox_file_data_size’ [-Wimplicit-function-declaration]
     len = MIN((size_t)tox_file_data_size(xfer_data->tox,
                       ^
/usr/include/glib-2.0/glib/gmacros.h:240:23: note: in definition of macro ‘MIN’
 #define MIN(a, b)  (((a) < (b)) ? (a) : (b))
                       ^
../src/toxprpl.c:1853:15: warning: implicit declaration of function ‘tox_file_send_data’ [-Wimplicit-function-declaration]
     int ret = tox_file_send_data(xfer_data->tox, xfer_data->friendnumber,
               ^
../src/toxprpl.c: In function ‘toxprpl_xfer_cancel_send’:
../src/toxprpl.c:1899:39: error: ‘TOX_FILECONTROL_KILL’ undeclared (first use in this function)
             0, xfer_data->filenumber, TOX_FILECONTROL_KILL, NULL, 0);
                                       ^
../src/toxprpl.c: In function ‘toxprpl_xfer_cancel_recv’:
../src/toxprpl.c:1913:39: error: ‘TOX_FILECONTROL_KILL’ undeclared (first use in this function)
             1, xfer_data->filenumber, TOX_FILECONTROL_KILL, NULL, 0);
                                       ^
../src/toxprpl.c: In function ‘toxprpl_xfer_request_denied’:
../src/toxprpl.c:1928:36: error: ‘TOX_FILECONTROL_KILL’ undeclared (first use in this function)
             xfer_data->filenumber, TOX_FILECONTROL_KILL, NULL, 0);
                                    ^
../src/toxprpl.c: In function ‘toxprpl_xfer_end’:
../src/toxprpl.c:1942:39: error: ‘TOX_FILECONTROL_FINISHED’ undeclared (first use in this function)
             0, xfer_data->filenumber, TOX_FILECONTROL_FINISHED, NULL, 0);
                                       ^
../src/toxprpl.c: In function ‘toxprpl_send_typing’:
../src/toxprpl.c:2065:13: warning: implicit declaration of function ‘tox_set_user_is_typing’ [-Wimplicit-function-declaration]
             tox_set_user_is_typing(plugin->tox, buddy_data->tox_friendlist_numb
             ^
Makefile:460: recipe for target 'libtox_la-toxprpl.lo' failed
make[2]: *** [libtox_la-toxprpl.lo] Error 1
make[2]: Leaving directory '/home/haozeke/Github/Pidgin/Tox/tox-prpl/build'
Makefile:415: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/haozeke/Github/Pidgin/Tox/tox-prpl'
Makefile:345: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jin-eld** [comment]
The plugin is not migrated to the new Tox API, there is already a ticket
for it, please close this one.

**Comment by HaoZeke** [comment]
Sure, sorry for not checking first..
