### ISSUE TITLE
which tox

### ISSUE THREAD

**Issue by qamble** [jin-eld/tox-prpl#60]
Which tox project is the one to use?  

There is a bit too much prattling on tox blogs to sort out the truth.

**Comment by Xylemon** [comment]
Not this one considering it doesn't function at the moment. uTox is lightweight while having a lot of standard Tox client features. qTox is bit more hefty but has some more features. Please look here for a list/comparison: https://wiki.tox.chat/clients

**Comment by jin-eld** [comment]
I am actually quite happy with qTox, but otherwise indeed, just pick one from the above link. As for tox_prpl,  I'll update this plugin soon, I received a code contribution that syncs to the latest Tox API.
